### ISSUE TITLE
UI tweaks for icon-species page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#168]
The 2 columns for https://lists-test.ala.org.au/iconic-species are overlapping for "normal width screens".
 
![image](https://user-images.githubusercontent.com/532845/88121079-02fa8a80-cc08-11ea-9605-144751109336.png)

- [ ] Fix the main column so it doesn't overlap with the left column - remove rules (?)
```css
.bs-docs-sidenav {
    width: 258px;
}

.bs-docs-sidenav {
    width: 228px;
```
- [ ] Reduce the size of the species image icons, so more are visible "above the fold" - remove rule (?):

```css
.imgCon img {
    height: 300px;
}
```
